version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: reader-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: reader
      MYSQL_DATABASE: reader
      MYSQL_USER: reader
      MYSQL_PASSWORD: reader
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - reader-network

volumes:
  mysql_data:
    driver: local

networks:
  reader-network:
    driver: bridge