ALTER TABLE book_metadata ALTER COLUMN title TYPE VARCHAR(1000);
ALTER TABLE book_metadata ALTER COLUMN subtitle TYPE VARCHAR(1000);
ALTER TABLE book_metadata ALTER COLUMN publisher TYPE VARCHAR(1000);
ALTER TABLE book_metadata ALTER COLUMN isbn_10 TYPE VARCHAR(64);
ALTER TABLE book_metadata ALTER COLUMN isbn_13 TYPE VARCHAR(64);
ALTER TABLE book_metadata ALTER COLUMN thumbnail TYPE VARCHAR(2000);
ALTER TABLE book_metadata ALTER COLUMN series_name TYPE VARCHAR(1000);
ALTER TABLE book_metadata ALTER COLUMN cover TYPE VARCHAR(2000);